### ISSUE TITLE
Its the same, awaiting login forever.... Game is english, keyboard english.. What should i do?

### ISSUE THREAD

**Issue by Krevzy** [Krach64/lol-bot-leveling-free#1]

**Comment by Krach64** [comment]
Where do you launch python main.py?

**Comment by Krach64** [comment]
I think you launch it in the wrong place, don't launch it in the folder of main.py

**Comment by Krevzy** [comment]
I launch from there: "C:\Users\Krevzy\Desktop\lol-bot-leveling-free-master"
with "python ./lol-leveling-bot/main.py"

**Comment by Krach64** [comment]
Did you close the game before launching the bot?

**Comment by Krevzy** [comment]
Yes, i closed completely. https://imgur.com/a/7AfSoXI

**Comment by Krach64** [comment]
What is the resolution of your screen? 
What is the resolution on your launcher? called window size

**Comment by Krevzy** [comment]
Win res is 1920x1080, client 1600x900

**Comment by Krach64** [comment]
Ok this is the problem. Your client must be 1280x720.
I commit a last patch, download it, you can launch the bot by clicking on .bat

**Comment by Krach64** [comment]
Don't forget to close the issue if it works
